version: '3.9'

services:
  app:
    image: golang:latest
    container_name: calc
    working_dir: /go/src/calc
    stdin_open: true
    tty: true
    volumes:
      - .:/go/src/calc
    ports:
      - "8080:8080"

    environment:
      - API_PORT=8080

